let mysqlHelper = require('./mysql');
const {Knex} = require("knex");
let config={
    database_type:'mysql',
    database_config: {
        host: 'localhost',
        username: 'root',
        password: '',
        database: 'mock5'
    },
    token: ''
}
let mysql=new mysqlHelper(config);

let demoData=[{"id":1,"name":"Waly","email":"wmairs0@blogtalkradio.com"},
    {"id":2,"name":"Dyann","email":"dcharlesworth1@tuttocitta.it"},
    {"id":3,"name":"Darby","email":"dgurry2@themeforest.net"},
    {"id":4,"name":"Justinian","email":"jgudeman3@mozilla.com"},
    {"id":5,"name":"Prescott","email":"prowbottom4@blogspot.com"},
    {"id":6,"name":"Datha","email":"dorum5@thetimes.co.uk"},
    {"id":7,"name":"Vail","email":"vlinck6@mozilla.com"},
    {"id":8,"name":"Cthrine","email":"cgirardoni7@e-recht24.de"},
    {"id":9,"name":"Jermain","email":"jsawfoot8@europa.eu"},
    {"id":10,"name":"Elbert","email":"ekivelle9@cdbaby.com"},
    {"id":11,"name":"Ryann","email":"rhrachoveca@skype.com"},
    {"id":12,"name":"Martita","email":"mpennonib@posterous.com"},
    {"id":13,"name":"Cele","email":"cmcgillc@kickstarter.com"},
    {"id":14,"name":"Hanson","email":"hstonhewerd@cnbc.com"},
    {"id":15,"name":"Karin","email":"kquineye@fc2.com"},
    {"id":16,"name":"Melicent","email":"mbuchanf@list-manage.com"},
    {"id":17,"name":"Kariotta","email":"kdeyenhardtg@edublogs.org"},
    {"id":18,"name":"Winfred","email":"wmorforthh@ameblo.jp"},
    {"id":19,"name":"Daffy","email":"dswettenhami@geocities.com"},
    {"id":20,"name":"Jilly","email":"jheadsj@geocities.com"},
    {"id":21,"name":"Nadya","email":"nidalek@ucla.edu"},
    {"id":22,"name":"Heindrick","email":"hcahalanl@lycos.com"},
    {"id":23,"name":"Karel","email":"kprestagem@examiner.com"},
    {"id":24,"name":"Eddie","email":"erupeln@biblegateway.com"},
    {"id":25,"name":"Emmerich","email":"esergeaunto@economist.com"},
    {"id":26,"name":"Monika","email":"mchansonnaup@dailymail.co.uk"},
    {"id":27,"name":"Felicle","email":"fsushamsq@miibeian.gov.cn"},
    {"id":28,"name":"Ganny","email":"glympanyr@guardian.co.uk"},
    {"id":29,"name":"Ki","email":"ktauntons@loc.gov"},
    {"id":30,"name":"Griswold","email":"gmcsweeneyt@psu.edu"},
    {"id":31,"name":"Aloisia","email":"amarteu@hc360.com"},
    {"id":32,"name":"Francklyn","email":"fanderbruggev@wordpress.com"},
    {"id":33,"name":"Selby","email":"ssallierew@mysql.com"},
    {"id":34,"name":"Zandra","email":"zmacanex@goo.gl"},
    {"id":35,"name":"Melosa","email":"mshepstoney@mit.edu"},
    {"id":36,"name":"Zeb","email":"zbartocciz@feedburner.com"},
    {"id":37,"name":"Othella","email":"oseabourne10@ed.gov"},
    {"id":38,"name":"L;urette","email":"lmarcinkus11@europa.eu"},
    {"id":39,"name":"Beitris","email":"bboulsher12@ocn.ne.jp"},
    {"id":40,"name":"Larry","email":"lfuncheon13@godaddy.com"},
    {"id":41,"name":"Carolann","email":"cgreader14@addthis.com"},
    {"id":42,"name":"Addie","email":"awiffen15@tamu.edu"},
    {"id":43,"name":"Angil","email":"adilleway16@theglobeandmail.com"},
    {"id":44,"name":"Jacinthe","email":"jmuslim17@google.com.au"},
    {"id":45,"name":"Yorgos","email":"ybladge18@mtv.com"},
    {"id":46,"name":"Umeko","email":"uchinery19@storify.com"},
    {"id":47,"name":"Sherline","email":"stoulmin1a@etsy.com"},
    {"id":48,"name":"Mallory","email":"mmusgrave1b@google.nl"},
    {"id":49,"name":"Josias","email":"jmarcroft1c@geocities.com"},
    {"id":50,"name":"Corrianne","email":"cwillimont1d@scribd.com"},
    {"id":51,"name":"Gale","email":"garne1e@twitpic.com"},
    {"id":52,"name":"Flora","email":"fparnell1f@rambler.ru"},
    {"id":53,"name":"Dodie","email":"ddurward1g@go.com"},
    {"id":54,"name":"Buddie","email":"bprestidge1h@weebly.com"},
    {"id":55,"name":"Damian","email":"dswinburne1i@seattletimes.com"},
    {"id":56,"name":"Georgiana","email":"ghars1j@shop-pro.jp"},
    {"id":57,"name":"Libby","email":"lfassum1k@miitbeian.gov.cn"},
    {"id":58,"name":"Suellen","email":"sfairweather1l@rakuten.co.jp"},
    {"id":59,"name":"Brigham","email":"bdaldan1m@i2i.jp"},
    {"id":60,"name":"Amalia","email":"aandre1n@amazon.co.uk"},
    {"id":61,"name":"Rafaello","email":"rouchterlony1o@eepurl.com"},
    {"id":62,"name":"Emmey","email":"epainter1p@cafepress.com"},
    {"id":63,"name":"Midge","email":"mmcevoy1q@squarespace.com"},
    {"id":64,"name":"Chad","email":"ccuxon1r@lulu.com"},
    {"id":65,"name":"Jilli","email":"jbutterworth1s@psu.edu"},
    {"id":66,"name":"Aube","email":"aalston1t@phoca.cz"},
    {"id":67,"name":"Wanda","email":"wbim1u@adobe.com"},
    {"id":68,"name":"Christie","email":"clindro1v@nyu.edu"},
    {"id":69,"name":"Sheffie","email":"scarnalan1w@gizmodo.com"},
    {"id":70,"name":"Selinda","email":"sparysowna1x@utexas.edu"},
    {"id":71,"name":"Adore","email":"acuphus1y@wiley.com"},
    {"id":72,"name":"Cornell","email":"catterley1z@g.co"},
    {"id":73,"name":"Lowrance","email":"lbettinson20@va.gov"},
    {"id":74,"name":"Joseito","email":"jdublin21@psu.edu"},
    {"id":75,"name":"Shelby","email":"sboost22@newyorker.com"},
    {"id":76,"name":"Stephie","email":"stendahl23@liveinternet.ru"},
    {"id":77,"name":"Chrissy","email":"cshacklady24@loc.gov"},
    {"id":78,"name":"Jilleen","email":"jbruggen25@elegantthemes.com"},
    {"id":79,"name":"Bili","email":"blipman26@washingtonpost.com"},
    {"id":80,"name":"Tab","email":"tmacterlagh27@ftc.gov"},
    {"id":81,"name":"Lynsey","email":"lpeekevout28@icio.us"},
    {"id":82,"name":"Harv","email":"hgreest29@drupal.org"},
    {"id":83,"name":"Emiline","email":"eblaydes2a@gizmodo.com"},
    {"id":84,"name":"Angeli","email":"aface2b@npr.org"},
    {"id":85,"name":"Marji","email":"mhallmark2c@comsenz.com"},
    {"id":86,"name":"Gwynne","email":"gcramphorn2d@gov.uk"},
    {"id":87,"name":"Dalenna","email":"dvasyatkin2e@walmart.com"},
    {"id":88,"name":"Nickie","email":"nchatteris2f@ucoz.ru"},
    {"id":89,"name":"Karel","email":"knutbeam2g@elpais.com"},
    {"id":90,"name":"Tammy","email":"tharbron2h@weather.com"},
    {"id":91,"name":"Johna","email":"jbaldetti2i@seesaa.net"},
    {"id":92,"name":"Ashla","email":"adenslow2j@de.vu"},
    {"id":93,"name":"Isobel","email":"ilovekin2k@spiegel.de"},
    {"id":94,"name":"Iggy","email":"isquires2l@oakley.com"},
    {"id":95,"name":"Mario","email":"mbinny2m@themeforest.net"},
    {"id":96,"name":"Cammy","email":"cfollows2n@nydailynews.com"},
    {"id":97,"name":"Farrel","email":"ffaas2o@thetimes.co.uk"},
    {"id":98,"name":"Virgil","email":"vmantle2p@t.co"},
    {"id":99,"name":"Thorin","email":"tpreuvost2q@yale.edu"},
    {"id":100,"name":"Roland","email":"rbastable2r@arizona.edu"}];

console.log("running insert test");
for (var i = 0; i < demoData.length; i++) {
    mysql.encryptedInsert('demo',['id','name','email'],[demoData[i].id,demoData[i].name,demoData[i].email]);
}


